package com.digits.sdk.android;

import android.support.v4.view.InputDeviceCompat;
import android.text.TextUtils;
import com.alipay.sdk.cons.C0844a;
import com.avos.avoscloud.AVException;
import com.baidu.mapapi.UIMsg.d_ResultType;
import com.google.i18n.phonenumbers.PhoneNumberUtil;
import com.google.zxing.client.result.ExpandedProductParsedResult;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.apache.http.HttpStatus;
import org.slf4j.Marker;

/* compiled from: PhoneNumberUtils */
class bo {
    /* renamed from: a */
    private final bt f13292a;

    bo(bt btVar) {
        this.f13292a = btVar;
    }

    /* renamed from: a */
    protected bi m14145a() {
        if (this.f13292a == null) {
            return bi.m14098a();
        }
        return m14138a(m14144c());
    }

    /* renamed from: a */
    protected bi m14146a(String str) {
        if (TextUtils.isEmpty(str)) {
            return m14145a();
        }
        String str2 = C0844a.f2048d;
        String str3 = "US";
        if (str.startsWith(Marker.ANY_NON_NULL_MARKER)) {
            Map b = m14143b();
            str2 = m14142b(b, str);
            str3 = m14141a(b, str2);
            str = m14139a(str, str2);
        }
        return new bi(str, str3, str2);
    }

    /* renamed from: a */
    private String m14141a(Map<Integer, List<String>> map, String str) {
        List list = (List) map.get(Integer.valueOf(str));
        if (list != null) {
            return (String) list.get(0);
        }
        return "US";
    }

    /* renamed from: b */
    private String m14142b(Map<Integer, List<String>> map, String str) {
        String replaceFirst = str.replaceFirst("^\\+", "");
        int length = replaceFirst.length();
        int i = 1;
        while (i <= 3 && i <= length) {
            String substring = replaceFirst.substring(0, i);
            if (map.containsKey(Integer.valueOf(substring))) {
                return substring;
            }
            i++;
        }
        return C0844a.f2048d;
    }

    /* renamed from: a */
    private bi m14138a(Map<String, Integer> map) {
        String b = this.f13292a.m14173b();
        String a = m14140a(b, (Map) map);
        return new bi(m14139a(this.f13292a.m14172a(), a), b, a);
    }

    /* renamed from: b */
    private Map<Integer, List<String>> m14143b() {
        Map<Integer, List<String>> hashMap = new HashMap(286);
        ArrayList arrayList = new ArrayList(25);
        arrayList.add("US");
        arrayList.add("AG");
        arrayList.add("AI");
        arrayList.add("AS");
        arrayList.add("BB");
        arrayList.add("BM");
        arrayList.add("BS");
        arrayList.add("CA");
        arrayList.add("DM");
        arrayList.add("DO");
        arrayList.add("GD");
        arrayList.add("GU");
        arrayList.add("JM");
        arrayList.add("KN");
        arrayList.add("KY");
        arrayList.add("LC");
        arrayList.add("MP");
        arrayList.add("MS");
        arrayList.add("PR");
        arrayList.add("SX");
        arrayList.add("TC");
        arrayList.add("TT");
        arrayList.add("VC");
        arrayList.add("VG");
        arrayList.add("VI");
        hashMap.put(Integer.valueOf(1), arrayList);
        arrayList = new ArrayList(2);
        arrayList.add("RU");
        arrayList.add("KZ");
        hashMap.put(Integer.valueOf(7), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("EG");
        hashMap.put(Integer.valueOf(20), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ZA");
        hashMap.put(Integer.valueOf(27), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GR");
        hashMap.put(Integer.valueOf(30), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NL");
        hashMap.put(Integer.valueOf(31), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BE");
        hashMap.put(Integer.valueOf(32), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("FR");
        hashMap.put(Integer.valueOf(33), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ES");
        hashMap.put(Integer.valueOf(34), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("HU");
        hashMap.put(Integer.valueOf(36), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("IT");
        hashMap.put(Integer.valueOf(39), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("RO");
        hashMap.put(Integer.valueOf(40), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CH");
        hashMap.put(Integer.valueOf(41), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AT");
        hashMap.put(Integer.valueOf(43), arrayList);
        arrayList = new ArrayList(4);
        arrayList.add("GB");
        arrayList.add("GG");
        arrayList.add("IM");
        arrayList.add("JE");
        hashMap.put(Integer.valueOf(44), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("DK");
        hashMap.put(Integer.valueOf(45), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SE");
        hashMap.put(Integer.valueOf(46), arrayList);
        arrayList = new ArrayList(2);
        arrayList.add("NO");
        arrayList.add("SJ");
        hashMap.put(Integer.valueOf(47), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PL");
        hashMap.put(Integer.valueOf(48), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("DE");
        hashMap.put(Integer.valueOf(49), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PE");
        hashMap.put(Integer.valueOf(51), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MX");
        hashMap.put(Integer.valueOf(52), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CU");
        hashMap.put(Integer.valueOf(53), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AR");
        hashMap.put(Integer.valueOf(54), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BR");
        hashMap.put(Integer.valueOf(55), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CL");
        hashMap.put(Integer.valueOf(56), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CO");
        hashMap.put(Integer.valueOf(57), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("VE");
        hashMap.put(Integer.valueOf(58), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MY");
        hashMap.put(Integer.valueOf(60), arrayList);
        arrayList = new ArrayList(3);
        arrayList.add("AU");
        arrayList.add("CC");
        arrayList.add("CX");
        hashMap.put(Integer.valueOf(61), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ID");
        hashMap.put(Integer.valueOf(62), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PH");
        hashMap.put(Integer.valueOf(63), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NZ");
        hashMap.put(Integer.valueOf(64), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SG");
        hashMap.put(Integer.valueOf(65), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TH");
        hashMap.put(Integer.valueOf(66), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("JP");
        hashMap.put(Integer.valueOf(81), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("KR");
        hashMap.put(Integer.valueOf(82), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("VN");
        hashMap.put(Integer.valueOf(84), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CN");
        hashMap.put(Integer.valueOf(86), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TR");
        hashMap.put(Integer.valueOf(90), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("IN");
        hashMap.put(Integer.valueOf(91), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PK");
        hashMap.put(Integer.valueOf(92), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AF");
        hashMap.put(Integer.valueOf(93), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LK");
        hashMap.put(Integer.valueOf(94), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MM");
        hashMap.put(Integer.valueOf(95), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("IR");
        hashMap.put(Integer.valueOf(98), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SS");
        hashMap.put(Integer.valueOf(AVException.USER_DOESNOT_EXIST), arrayList);
        arrayList = new ArrayList(2);
        arrayList.add("MA");
        arrayList.add("EH");
        hashMap.put(Integer.valueOf(AVException.USER_MOBILEPHONE_MISSING), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("DZ");
        hashMap.put(Integer.valueOf(AVException.USER_WITH_MOBILEPHONE_NOT_FOUND), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TN");
        hashMap.put(Integer.valueOf(216), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LY");
        hashMap.put(Integer.valueOf(218), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GM");
        hashMap.put(Integer.valueOf(220), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SN");
        hashMap.put(Integer.valueOf(221), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MR");
        hashMap.put(Integer.valueOf(222), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ML");
        hashMap.put(Integer.valueOf(223), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GN");
        hashMap.put(Integer.valueOf(224), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CI");
        hashMap.put(Integer.valueOf(225), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BF");
        hashMap.put(Integer.valueOf(226), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NE");
        hashMap.put(Integer.valueOf(227), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TG");
        hashMap.put(Integer.valueOf(228), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BJ");
        hashMap.put(Integer.valueOf(229), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MU");
        hashMap.put(Integer.valueOf(230), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LR");
        hashMap.put(Integer.valueOf(231), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SL");
        hashMap.put(Integer.valueOf(232), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GH");
        hashMap.put(Integer.valueOf(233), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NG");
        hashMap.put(Integer.valueOf(234), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TD");
        hashMap.put(Integer.valueOf(235), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CF");
        hashMap.put(Integer.valueOf(236), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CM");
        hashMap.put(Integer.valueOf(237), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CV");
        hashMap.put(Integer.valueOf(238), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ST");
        hashMap.put(Integer.valueOf(239), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GQ");
        hashMap.put(Integer.valueOf(240), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GA");
        hashMap.put(Integer.valueOf(241), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CG");
        hashMap.put(Integer.valueOf(242), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CD");
        hashMap.put(Integer.valueOf(243), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AO");
        hashMap.put(Integer.valueOf(244), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GW");
        hashMap.put(Integer.valueOf(245), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("IO");
        hashMap.put(Integer.valueOf(246), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AC");
        hashMap.put(Integer.valueOf(247), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SC");
        hashMap.put(Integer.valueOf(248), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SD");
        hashMap.put(Integer.valueOf(249), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("RW");
        hashMap.put(Integer.valueOf(250), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ET");
        hashMap.put(Integer.valueOf(AVException.INVALID_LINKED_SESSION), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SO");
        hashMap.put(Integer.valueOf(AVException.UNSUPPORTED_SERVICE), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("DJ");
        hashMap.put(Integer.valueOf(AVException.FILE_DOWNLOAD_INCONSISTENT_FAILURE), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("KE");
        hashMap.put(Integer.valueOf(254), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TZ");
        hashMap.put(Integer.valueOf(255), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("UG");
        hashMap.put(Integer.valueOf(256), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BI");
        hashMap.put(Integer.valueOf(InputDeviceCompat.SOURCE_KEYBOARD), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MZ");
        hashMap.put(Integer.valueOf(258), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ZM");
        hashMap.put(Integer.valueOf(260), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MG");
        hashMap.put(Integer.valueOf(261), arrayList);
        arrayList = new ArrayList(2);
        arrayList.add("RE");
        arrayList.add("YT");
        hashMap.put(Integer.valueOf(262), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ZW");
        hashMap.put(Integer.valueOf(263), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NA");
        hashMap.put(Integer.valueOf(264), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MW");
        hashMap.put(Integer.valueOf(265), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LS");
        hashMap.put(Integer.valueOf(266), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BW");
        hashMap.put(Integer.valueOf(267), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SZ");
        hashMap.put(Integer.valueOf(268), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("KM");
        hashMap.put(Integer.valueOf(269), arrayList);
        arrayList = new ArrayList(2);
        arrayList.add("SH");
        arrayList.add("TA");
        hashMap.put(Integer.valueOf(290), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ER");
        hashMap.put(Integer.valueOf(291), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AW");
        hashMap.put(Integer.valueOf(297), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("FO");
        hashMap.put(Integer.valueOf(298), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GL");
        hashMap.put(Integer.valueOf(299), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GI");
        hashMap.put(Integer.valueOf(350), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PT");
        hashMap.put(Integer.valueOf(351), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LU");
        hashMap.put(Integer.valueOf(352), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("IE");
        hashMap.put(Integer.valueOf(353), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("IS");
        hashMap.put(Integer.valueOf(354), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AL");
        hashMap.put(Integer.valueOf(355), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MT");
        hashMap.put(Integer.valueOf(356), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CY");
        hashMap.put(Integer.valueOf(357), arrayList);
        arrayList = new ArrayList(2);
        arrayList.add("FI");
        arrayList.add("AX");
        hashMap.put(Integer.valueOf(358), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BG");
        hashMap.put(Integer.valueOf(359), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LT");
        hashMap.put(Integer.valueOf(370), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LV");
        hashMap.put(Integer.valueOf(371), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("EE");
        hashMap.put(Integer.valueOf(372), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MD");
        hashMap.put(Integer.valueOf(373), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AM");
        hashMap.put(Integer.valueOf(374), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BY");
        hashMap.put(Integer.valueOf(375), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AD");
        hashMap.put(Integer.valueOf(376), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MC");
        hashMap.put(Integer.valueOf(377), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SM");
        hashMap.put(Integer.valueOf(378), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("VA");
        hashMap.put(Integer.valueOf(379), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("UA");
        hashMap.put(Integer.valueOf(380), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("RS");
        hashMap.put(Integer.valueOf(381), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("ME");
        hashMap.put(Integer.valueOf(382), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("HR");
        hashMap.put(Integer.valueOf(385), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SI");
        hashMap.put(Integer.valueOf(386), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BA");
        hashMap.put(Integer.valueOf(387), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MK");
        hashMap.put(Integer.valueOf(389), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CZ");
        hashMap.put(Integer.valueOf(HttpStatus.SC_METHOD_FAILURE), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SK");
        hashMap.put(Integer.valueOf(421), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LI");
        hashMap.put(Integer.valueOf(HttpStatus.SC_LOCKED), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("FK");
        hashMap.put(Integer.valueOf(500), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BZ");
        hashMap.put(Integer.valueOf(501), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GT");
        hashMap.put(Integer.valueOf(502), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SV");
        hashMap.put(Integer.valueOf(503), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("HN");
        hashMap.put(Integer.valueOf(504), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NI");
        hashMap.put(Integer.valueOf(505), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CR");
        hashMap.put(Integer.valueOf(d_ResultType.SUGGESTION_SEARCH), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PA");
        hashMap.put(Integer.valueOf(507), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PM");
        hashMap.put(Integer.valueOf(d_ResultType.LONG_URL), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("HT");
        hashMap.put(Integer.valueOf(509), arrayList);
        arrayList = new ArrayList(3);
        arrayList.add("GP");
        arrayList.add("BL");
        arrayList.add("MF");
        hashMap.put(Integer.valueOf(590), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BO");
        hashMap.put(Integer.valueOf(591), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GY");
        hashMap.put(Integer.valueOf(592), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("EC");
        hashMap.put(Integer.valueOf(593), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GF");
        hashMap.put(Integer.valueOf(594), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PY");
        hashMap.put(Integer.valueOf(595), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MQ");
        hashMap.put(Integer.valueOf(596), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SR");
        hashMap.put(Integer.valueOf(597), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("UY");
        hashMap.put(Integer.valueOf(598), arrayList);
        arrayList = new ArrayList(2);
        arrayList.add("CW");
        arrayList.add("BQ");
        hashMap.put(Integer.valueOf(599), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TL");
        hashMap.put(Integer.valueOf(670), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NF");
        hashMap.put(Integer.valueOf(672), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BN");
        hashMap.put(Integer.valueOf(673), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NR");
        hashMap.put(Integer.valueOf(674), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PG");
        hashMap.put(Integer.valueOf(675), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TO");
        hashMap.put(Integer.valueOf(676), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SB");
        hashMap.put(Integer.valueOf(677), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("VU");
        hashMap.put(Integer.valueOf(678), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("FJ");
        hashMap.put(Integer.valueOf(679), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PW");
        hashMap.put(Integer.valueOf(680), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("WF");
        hashMap.put(Integer.valueOf(681), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("CK");
        hashMap.put(Integer.valueOf(682), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NU");
        hashMap.put(Integer.valueOf(683), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("WS");
        hashMap.put(Integer.valueOf(685), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("KI");
        hashMap.put(Integer.valueOf(686), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NC");
        hashMap.put(Integer.valueOf(687), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TV");
        hashMap.put(Integer.valueOf(688), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PF");
        hashMap.put(Integer.valueOf(689), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TK");
        hashMap.put(Integer.valueOf(690), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("FM");
        hashMap.put(Integer.valueOf(691), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MH");
        hashMap.put(Integer.valueOf(692), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(800), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(808), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("KP");
        hashMap.put(Integer.valueOf(850), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("HK");
        hashMap.put(Integer.valueOf(852), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MO");
        hashMap.put(Integer.valueOf(853), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("KH");
        hashMap.put(Integer.valueOf(855), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("LA");
        hashMap.put(Integer.valueOf(856), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(870), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(878), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BD");
        hashMap.put(Integer.valueOf(880), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(881), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(882), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(883), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TW");
        hashMap.put(Integer.valueOf(886), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(888), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MV");
        hashMap.put(Integer.valueOf(960), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(ExpandedProductParsedResult.POUND);
        hashMap.put(Integer.valueOf(961), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("JO");
        hashMap.put(Integer.valueOf(962), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SY");
        hashMap.put(Integer.valueOf(963), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("IQ");
        hashMap.put(Integer.valueOf(964), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("KW");
        hashMap.put(Integer.valueOf(965), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("SA");
        hashMap.put(Integer.valueOf(966), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("YE");
        hashMap.put(Integer.valueOf(967), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("OM");
        hashMap.put(Integer.valueOf(968), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("PS");
        hashMap.put(Integer.valueOf(970), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AE");
        hashMap.put(Integer.valueOf(971), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("IL");
        hashMap.put(Integer.valueOf(972), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BH");
        hashMap.put(Integer.valueOf(973), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("QA");
        hashMap.put(Integer.valueOf(974), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("BT");
        hashMap.put(Integer.valueOf(975), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("MN");
        hashMap.put(Integer.valueOf(976), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("NP");
        hashMap.put(Integer.valueOf(977), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(PhoneNumberUtil.REGION_CODE_FOR_NON_GEO_ENTITY);
        hashMap.put(Integer.valueOf(979), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TJ");
        hashMap.put(Integer.valueOf(992), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("TM");
        hashMap.put(Integer.valueOf(993), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("AZ");
        hashMap.put(Integer.valueOf(994), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("GE");
        hashMap.put(Integer.valueOf(995), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add(ExpandedProductParsedResult.KILOGRAM);
        hashMap.put(Integer.valueOf(996), arrayList);
        arrayList = new ArrayList(1);
        arrayList.add("UZ");
        hashMap.put(Integer.valueOf(998), arrayList);
        return hashMap;
    }

    /* renamed from: c */
    private Map<String, Integer> m14144c() {
        Map<String, Integer> hashMap = new HashMap(291);
        hashMap.put("AF", Integer.valueOf(93));
        hashMap.put("AX", Integer.valueOf(358));
        hashMap.put("AL", Integer.valueOf(355));
        hashMap.put("DZ", Integer.valueOf(AVException.USER_WITH_MOBILEPHONE_NOT_FOUND));
        hashMap.put("AS", Integer.valueOf(1));
        hashMap.put("AD", Integer.valueOf(376));
        hashMap.put("AO", Integer.valueOf(244));
        hashMap.put("AI", Integer.valueOf(1));
        hashMap.put("AG", Integer.valueOf(1));
        hashMap.put("AR", Integer.valueOf(54));
        hashMap.put("AM", Integer.valueOf(374));
        hashMap.put("AW", Integer.valueOf(297));
        hashMap.put("AC", Integer.valueOf(247));
        hashMap.put("AU", Integer.valueOf(61));
        hashMap.put("AT", Integer.valueOf(43));
        hashMap.put("AZ", Integer.valueOf(994));
        hashMap.put("BS", Integer.valueOf(1));
        hashMap.put("BH", Integer.valueOf(973));
        hashMap.put("BD", Integer.valueOf(880));
        hashMap.put("BB", Integer.valueOf(1));
        hashMap.put("BY", Integer.valueOf(375));
        hashMap.put("BE", Integer.valueOf(32));
        hashMap.put("BZ", Integer.valueOf(501));
        hashMap.put("BJ", Integer.valueOf(229));
        hashMap.put("BM", Integer.valueOf(1));
        hashMap.put("BT", Integer.valueOf(975));
        hashMap.put("BO", Integer.valueOf(591));
        hashMap.put("BA", Integer.valueOf(387));
        hashMap.put("BW", Integer.valueOf(267));
        hashMap.put("BR", Integer.valueOf(55));
        hashMap.put("IO", Integer.valueOf(246));
        hashMap.put("VG", Integer.valueOf(1));
        hashMap.put("BN", Integer.valueOf(673));
        hashMap.put("BG", Integer.valueOf(359));
        hashMap.put("BF", Integer.valueOf(226));
        hashMap.put("BI", Integer.valueOf(InputDeviceCompat.SOURCE_KEYBOARD));
        hashMap.put("KH", Integer.valueOf(855));
        hashMap.put("CM", Integer.valueOf(237));
        hashMap.put("CA", Integer.valueOf(1));
        hashMap.put("CV", Integer.valueOf(238));
        hashMap.put("BQ", Integer.valueOf(599));
        hashMap.put("KY", Integer.valueOf(1));
        hashMap.put("CF", Integer.valueOf(236));
        hashMap.put("TD", Integer.valueOf(235));
        hashMap.put("CL", Integer.valueOf(56));
        hashMap.put("CN", Integer.valueOf(86));
        hashMap.put("CX", Integer.valueOf(61));
        hashMap.put("CC", Integer.valueOf(61));
        hashMap.put("CO", Integer.valueOf(57));
        hashMap.put("KM", Integer.valueOf(269));
        hashMap.put("CD", Integer.valueOf(243));
        hashMap.put("CG", Integer.valueOf(242));
        hashMap.put("CK", Integer.valueOf(682));
        hashMap.put("CR", Integer.valueOf(d_ResultType.SUGGESTION_SEARCH));
        hashMap.put("CI", Integer.valueOf(225));
        hashMap.put("HR", Integer.valueOf(385));
        hashMap.put("CU", Integer.valueOf(53));
        hashMap.put("CW", Integer.valueOf(599));
        hashMap.put("CY", Integer.valueOf(357));
        hashMap.put("CZ", Integer.valueOf(HttpStatus.SC_METHOD_FAILURE));
        hashMap.put("DK", Integer.valueOf(45));
        hashMap.put("DJ", Integer.valueOf(AVException.FILE_DOWNLOAD_INCONSISTENT_FAILURE));
        hashMap.put("DM", Integer.valueOf(1));
        hashMap.put("DO", Integer.valueOf(1));
        hashMap.put("TL", Integer.valueOf(670));
        hashMap.put("EC", Integer.valueOf(593));
        hashMap.put("EG", Integer.valueOf(20));
        hashMap.put("SV", Integer.valueOf(503));
        hashMap.put("GQ", Integer.valueOf(240));
        hashMap.put("ER", Integer.valueOf(291));
        hashMap.put("EE", Integer.valueOf(372));
        hashMap.put("ET", Integer.valueOf(AVException.INVALID_LINKED_SESSION));
        hashMap.put("FK", Integer.valueOf(500));
        hashMap.put("FO", Integer.valueOf(298));
        hashMap.put("FJ", Integer.valueOf(679));
        hashMap.put("FI", Integer.valueOf(358));
        hashMap.put("FR", Integer.valueOf(33));
        hashMap.put("GF", Integer.valueOf(594));
        hashMap.put("PF", Integer.valueOf(689));
        hashMap.put("GA", Integer.valueOf(241));
        hashMap.put("GM", Integer.valueOf(220));
        hashMap.put("GE", Integer.valueOf(995));
        hashMap.put("DE", Integer.valueOf(49));
        hashMap.put("GH", Integer.valueOf(233));
        hashMap.put("GI", Integer.valueOf(350));
        hashMap.put("GR", Integer.valueOf(30));
        hashMap.put("GL", Integer.valueOf(299));
        hashMap.put("GD", Integer.valueOf(1));
        hashMap.put("GP", Integer.valueOf(590));
        hashMap.put("GU", Integer.valueOf(1));
        hashMap.put("GT", Integer.valueOf(502));
        hashMap.put("GG", Integer.valueOf(44));
        hashMap.put("GN", Integer.valueOf(224));
        hashMap.put("GW", Integer.valueOf(245));
        hashMap.put("GY", Integer.valueOf(592));
        hashMap.put("HT", Integer.valueOf(509));
        hashMap.put("HM", Integer.valueOf(672));
        hashMap.put("HN", Integer.valueOf(504));
        hashMap.put("HK", Integer.valueOf(852));
        hashMap.put("HU", Integer.valueOf(36));
        hashMap.put("IS", Integer.valueOf(354));
        hashMap.put("IN", Integer.valueOf(91));
        hashMap.put("ID", Integer.valueOf(62));
        hashMap.put("IR", Integer.valueOf(98));
        hashMap.put("IQ", Integer.valueOf(964));
        hashMap.put("IE", Integer.valueOf(353));
        hashMap.put("IM", Integer.valueOf(44));
        hashMap.put("IL", Integer.valueOf(972));
        hashMap.put("IT", Integer.valueOf(39));
        hashMap.put("JM", Integer.valueOf(1));
        hashMap.put("JP", Integer.valueOf(81));
        hashMap.put("JE", Integer.valueOf(44));
        hashMap.put("JO", Integer.valueOf(962));
        hashMap.put("KZ", Integer.valueOf(7));
        hashMap.put("KE", Integer.valueOf(254));
        hashMap.put("KI", Integer.valueOf(686));
        hashMap.put("XK", Integer.valueOf(381));
        hashMap.put("KW", Integer.valueOf(965));
        hashMap.put(ExpandedProductParsedResult.KILOGRAM, Integer.valueOf(996));
        hashMap.put("LA", Integer.valueOf(856));
        hashMap.put("LV", Integer.valueOf(371));
        hashMap.put(ExpandedProductParsedResult.POUND, Integer.valueOf(961));
        hashMap.put("LS", Integer.valueOf(266));
        hashMap.put("LR", Integer.valueOf(231));
        hashMap.put("LY", Integer.valueOf(218));
        hashMap.put("LI", Integer.valueOf(HttpStatus.SC_LOCKED));
        hashMap.put("LT", Integer.valueOf(370));
        hashMap.put("LU", Integer.valueOf(352));
        hashMap.put("MO", Integer.valueOf(853));
        hashMap.put("MK", Integer.valueOf(389));
        hashMap.put("MG", Integer.valueOf(261));
        hashMap.put("MW", Integer.valueOf(265));
        hashMap.put("MY", Integer.valueOf(60));
        hashMap.put("MV", Integer.valueOf(960));
        hashMap.put("ML", Integer.valueOf(223));
        hashMap.put("MT", Integer.valueOf(356));
        hashMap.put("MH", Integer.valueOf(692));
        hashMap.put("MQ", Integer.valueOf(596));
        hashMap.put("MR", Integer.valueOf(222));
        hashMap.put("MU", Integer.valueOf(230));
        hashMap.put("YT", Integer.valueOf(262));
        hashMap.put("MX", Integer.valueOf(52));
        hashMap.put("FM", Integer.valueOf(691));
        hashMap.put("MD", Integer.valueOf(373));
        hashMap.put("MC", Integer.valueOf(377));
        hashMap.put("MN", Integer.valueOf(976));
        hashMap.put("ME", Integer.valueOf(382));
        hashMap.put("MS", Integer.valueOf(1));
        hashMap.put("MA", Integer.valueOf(AVException.USER_MOBILEPHONE_MISSING));
        hashMap.put("MZ", Integer.valueOf(258));
        hashMap.put("MM", Integer.valueOf(95));
        hashMap.put("NA", Integer.valueOf(264));
        hashMap.put("NR", Integer.valueOf(674));
        hashMap.put("NP", Integer.valueOf(977));
        hashMap.put("NL", Integer.valueOf(31));
        hashMap.put("NC", Integer.valueOf(687));
        hashMap.put("NZ", Integer.valueOf(64));
        hashMap.put("NI", Integer.valueOf(505));
        hashMap.put("NE", Integer.valueOf(227));
        hashMap.put("NG", Integer.valueOf(234));
        hashMap.put("NU", Integer.valueOf(683));
        hashMap.put("NF", Integer.valueOf(672));
        hashMap.put("KP", Integer.valueOf(850));
        hashMap.put("MP", Integer.valueOf(1));
        hashMap.put("NO", Integer.valueOf(47));
        hashMap.put("OM", Integer.valueOf(968));
        hashMap.put("PK", Integer.valueOf(92));
        hashMap.put("PW", Integer.valueOf(680));
        hashMap.put("PS", Integer.valueOf(970));
        hashMap.put("PA", Integer.valueOf(507));
        hashMap.put("PG", Integer.valueOf(675));
        hashMap.put("PY", Integer.valueOf(595));
        hashMap.put("PE", Integer.valueOf(51));
        hashMap.put("PH", Integer.valueOf(63));
        hashMap.put("PL", Integer.valueOf(48));
        hashMap.put("PT", Integer.valueOf(351));
        hashMap.put("PR", Integer.valueOf(1));
        hashMap.put("QA", Integer.valueOf(974));
        hashMap.put("RE", Integer.valueOf(262));
        hashMap.put("RO", Integer.valueOf(40));
        hashMap.put("RU", Integer.valueOf(7));
        hashMap.put("RW", Integer.valueOf(250));
        hashMap.put("BL", Integer.valueOf(590));
        hashMap.put("SH", Integer.valueOf(290));
        hashMap.put("KN", Integer.valueOf(1));
        hashMap.put("LC", Integer.valueOf(1));
        hashMap.put("MF", Integer.valueOf(590));
        hashMap.put("PM", Integer.valueOf(d_ResultType.LONG_URL));
        hashMap.put("VC", Integer.valueOf(1));
        hashMap.put("WS", Integer.valueOf(685));
        hashMap.put("SM", Integer.valueOf(378));
        hashMap.put("ST", Integer.valueOf(239));
        hashMap.put("SA", Integer.valueOf(966));
        hashMap.put("SN", Integer.valueOf(221));
        hashMap.put("RS", Integer.valueOf(381));
        hashMap.put("SC", Integer.valueOf(248));
        hashMap.put("SL", Integer.valueOf(232));
        hashMap.put("SG", Integer.valueOf(65));
        hashMap.put("SX", Integer.valueOf(1));
        hashMap.put("SK", Integer.valueOf(421));
        hashMap.put("SI", Integer.valueOf(386));
        hashMap.put("SB", Integer.valueOf(677));
        hashMap.put("SO", Integer.valueOf(AVException.UNSUPPORTED_SERVICE));
        hashMap.put("ZA", Integer.valueOf(27));
        hashMap.put("GS", Integer.valueOf(500));
        hashMap.put("KR", Integer.valueOf(82));
        hashMap.put("SS", Integer.valueOf(AVException.USER_DOESNOT_EXIST));
        hashMap.put("ES", Integer.valueOf(34));
        hashMap.put("LK", Integer.valueOf(94));
        hashMap.put("SD", Integer.valueOf(249));
        hashMap.put("SR", Integer.valueOf(597));
        hashMap.put("SJ", Integer.valueOf(47));
        hashMap.put("SZ", Integer.valueOf(268));
        hashMap.put("SE", Integer.valueOf(46));
        hashMap.put("CH", Integer.valueOf(41));
        hashMap.put("SY", Integer.valueOf(963));
        hashMap.put("TW", Integer.valueOf(886));
        hashMap.put("TJ", Integer.valueOf(992));
        hashMap.put("TZ", Integer.valueOf(255));
        hashMap.put("TH", Integer.valueOf(66));
        hashMap.put("TG", Integer.valueOf(228));
        hashMap.put("TK", Integer.valueOf(690));
        hashMap.put("TO", Integer.valueOf(676));
        hashMap.put("TT", Integer.valueOf(1));
        hashMap.put("TN", Integer.valueOf(216));
        hashMap.put("TR", Integer.valueOf(90));
        hashMap.put("TM", Integer.valueOf(993));
        hashMap.put("TC", Integer.valueOf(1));
        hashMap.put("TV", Integer.valueOf(688));
        hashMap.put("VI", Integer.valueOf(1));
        hashMap.put("UG", Integer.valueOf(256));
        hashMap.put("UA", Integer.valueOf(380));
        hashMap.put("AE", Integer.valueOf(971));
        hashMap.put("GB", Integer.valueOf(44));
        hashMap.put("US", Integer.valueOf(1));
        hashMap.put("UY", Integer.valueOf(598));
        hashMap.put("UZ", Integer.valueOf(998));
        hashMap.put("VU", Integer.valueOf(678));
        hashMap.put("VA", Integer.valueOf(379));
        hashMap.put("VE", Integer.valueOf(58));
        hashMap.put("VN", Integer.valueOf(84));
        hashMap.put("WF", Integer.valueOf(681));
        hashMap.put("EH", Integer.valueOf(AVException.USER_MOBILEPHONE_MISSING));
        hashMap.put("YE", Integer.valueOf(967));
        hashMap.put("ZM", Integer.valueOf(260));
        hashMap.put("ZW", Integer.valueOf(263));
        return hashMap;
    }

    /* renamed from: a */
    private String m14140a(String str, Map<String, Integer> map) {
        if (str == null) {
            return "";
        }
        Integer num = (Integer) map.get(str.toUpperCase(Locale.getDefault()));
        return num == null ? "" : num.toString();
    }

    /* renamed from: a */
    private String m14139a(String str, String str2) {
        return str.replaceFirst("^\\+?" + str2, "");
    }
}
