package com.digits.sdk.android;

import android.support.v4.view.InputDeviceCompat;
import com.avos.avoscloud.AVException;
import com.baidu.mapapi.UIMsg.d_ResultType;
import com.google.zxing.client.result.ExpandedProductParsedResult;
import io.fabric.sdk.android.services.concurrency.AsyncTask;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import org.apache.http.HttpStatus;

/* compiled from: CountryListLoadTask */
/* renamed from: com.digits.sdk.android.y */
class C2937y extends AsyncTask<Void, Void, List<C2935w>> {
    /* renamed from: a */
    private final C2875a f13356a;

    /* compiled from: CountryListLoadTask */
    /* renamed from: com.digits.sdk.android.y$a */
    public interface C2875a {
        /* renamed from: a */
        void mo3631a(List<C2935w> list);
    }

    public C2937y(C2875a c2875a) {
        this.f13356a = c2875a;
    }

    /* renamed from: a */
    protected List<C2935w> m14263a(Void... voidArr) {
        List<C2935w> arrayList = new ArrayList(291);
        arrayList.add(new C2935w(new Locale("", "AF").getDisplayCountry(), 93));
        arrayList.add(new C2935w(new Locale("", "AX").getDisplayCountry(), 358));
        arrayList.add(new C2935w(new Locale("", "AL").getDisplayCountry(), 355));
        arrayList.add(new C2935w(new Locale("", "DZ").getDisplayCountry(), AVException.USER_WITH_MOBILEPHONE_NOT_FOUND));
        arrayList.add(new C2935w(new Locale("", "AS").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "AD").getDisplayCountry(), 376));
        arrayList.add(new C2935w(new Locale("", "AO").getDisplayCountry(), 244));
        arrayList.add(new C2935w(new Locale("", "AI").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "AG").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "AR").getDisplayCountry(), 54));
        arrayList.add(new C2935w(new Locale("", "AM").getDisplayCountry(), 374));
        arrayList.add(new C2935w(new Locale("", "AW").getDisplayCountry(), 297));
        arrayList.add(new C2935w(new Locale("", "AC").getDisplayCountry(), 247));
        arrayList.add(new C2935w(new Locale("", "AU").getDisplayCountry(), 61));
        arrayList.add(new C2935w(new Locale("", "AT").getDisplayCountry(), 43));
        arrayList.add(new C2935w(new Locale("", "AZ").getDisplayCountry(), 994));
        arrayList.add(new C2935w(new Locale("", "BS").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "BH").getDisplayCountry(), 973));
        arrayList.add(new C2935w(new Locale("", "BD").getDisplayCountry(), 880));
        arrayList.add(new C2935w(new Locale("", "BB").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "BY").getDisplayCountry(), 375));
        arrayList.add(new C2935w(new Locale("", "BE").getDisplayCountry(), 32));
        arrayList.add(new C2935w(new Locale("", "BZ").getDisplayCountry(), 501));
        arrayList.add(new C2935w(new Locale("", "BJ").getDisplayCountry(), 229));
        arrayList.add(new C2935w(new Locale("", "BM").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "BT").getDisplayCountry(), 975));
        arrayList.add(new C2935w(new Locale("", "BO").getDisplayCountry(), 591));
        arrayList.add(new C2935w(new Locale("", "BA").getDisplayCountry(), 387));
        arrayList.add(new C2935w(new Locale("", "BW").getDisplayCountry(), 267));
        arrayList.add(new C2935w(new Locale("", "BR").getDisplayCountry(), 55));
        arrayList.add(new C2935w(new Locale("", "IO").getDisplayCountry(), 246));
        arrayList.add(new C2935w(new Locale("", "VG").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "BN").getDisplayCountry(), 673));
        arrayList.add(new C2935w(new Locale("", "BG").getDisplayCountry(), 359));
        arrayList.add(new C2935w(new Locale("", "BF").getDisplayCountry(), 226));
        arrayList.add(new C2935w(new Locale("", "BI").getDisplayCountry(), InputDeviceCompat.SOURCE_KEYBOARD));
        arrayList.add(new C2935w(new Locale("", "KH").getDisplayCountry(), 855));
        arrayList.add(new C2935w(new Locale("", "CM").getDisplayCountry(), 237));
        arrayList.add(new C2935w(new Locale("", "CA").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "CV").getDisplayCountry(), 238));
        arrayList.add(new C2935w(new Locale("", "BQ").getDisplayCountry(), 599));
        arrayList.add(new C2935w(new Locale("", "KY").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "CF").getDisplayCountry(), 236));
        arrayList.add(new C2935w(new Locale("", "TD").getDisplayCountry(), 235));
        arrayList.add(new C2935w(new Locale("", "CL").getDisplayCountry(), 56));
        arrayList.add(new C2935w(new Locale("", "CN").getDisplayCountry(), 86));
        arrayList.add(new C2935w(new Locale("", "CX").getDisplayCountry(), 61));
        arrayList.add(new C2935w(new Locale("", "CC").getDisplayCountry(), 61));
        arrayList.add(new C2935w(new Locale("", "CO").getDisplayCountry(), 57));
        arrayList.add(new C2935w(new Locale("", "KM").getDisplayCountry(), 269));
        arrayList.add(new C2935w(new Locale("", "CD").getDisplayCountry(), 243));
        arrayList.add(new C2935w(new Locale("", "CG").getDisplayCountry(), 242));
        arrayList.add(new C2935w(new Locale("", "CK").getDisplayCountry(), 682));
        arrayList.add(new C2935w(new Locale("", "CR").getDisplayCountry(), d_ResultType.SUGGESTION_SEARCH));
        arrayList.add(new C2935w(new Locale("", "CI").getDisplayCountry(), 225));
        arrayList.add(new C2935w(new Locale("", "HR").getDisplayCountry(), 385));
        arrayList.add(new C2935w(new Locale("", "CU").getDisplayCountry(), 53));
        arrayList.add(new C2935w(new Locale("", "CW").getDisplayCountry(), 599));
        arrayList.add(new C2935w(new Locale("", "CY").getDisplayCountry(), 357));
        arrayList.add(new C2935w(new Locale("", "CZ").getDisplayCountry(), HttpStatus.SC_METHOD_FAILURE));
        arrayList.add(new C2935w(new Locale("", "DK").getDisplayCountry(), 45));
        arrayList.add(new C2935w(new Locale("", "DJ").getDisplayCountry(), AVException.FILE_DOWNLOAD_INCONSISTENT_FAILURE));
        arrayList.add(new C2935w(new Locale("", "DM").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "DO").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "TL").getDisplayCountry(), 670));
        arrayList.add(new C2935w(new Locale("", "EC").getDisplayCountry(), 593));
        arrayList.add(new C2935w(new Locale("", "EG").getDisplayCountry(), 20));
        arrayList.add(new C2935w(new Locale("", "SV").getDisplayCountry(), 503));
        arrayList.add(new C2935w(new Locale("", "GQ").getDisplayCountry(), 240));
        arrayList.add(new C2935w(new Locale("", "ER").getDisplayCountry(), 291));
        arrayList.add(new C2935w(new Locale("", "EE").getDisplayCountry(), 372));
        arrayList.add(new C2935w(new Locale("", "ET").getDisplayCountry(), AVException.INVALID_LINKED_SESSION));
        arrayList.add(new C2935w(new Locale("", "FK").getDisplayCountry(), 500));
        arrayList.add(new C2935w(new Locale("", "FO").getDisplayCountry(), 298));
        arrayList.add(new C2935w(new Locale("", "FJ").getDisplayCountry(), 679));
        arrayList.add(new C2935w(new Locale("", "FI").getDisplayCountry(), 358));
        arrayList.add(new C2935w(new Locale("", "FR").getDisplayCountry(), 33));
        arrayList.add(new C2935w(new Locale("", "GF").getDisplayCountry(), 594));
        arrayList.add(new C2935w(new Locale("", "PF").getDisplayCountry(), 689));
        arrayList.add(new C2935w(new Locale("", "GA").getDisplayCountry(), 241));
        arrayList.add(new C2935w(new Locale("", "GM").getDisplayCountry(), 220));
        arrayList.add(new C2935w(new Locale("", "GE").getDisplayCountry(), 995));
        arrayList.add(new C2935w(new Locale("", "DE").getDisplayCountry(), 49));
        arrayList.add(new C2935w(new Locale("", "GH").getDisplayCountry(), 233));
        arrayList.add(new C2935w(new Locale("", "GI").getDisplayCountry(), 350));
        arrayList.add(new C2935w(new Locale("", "GR").getDisplayCountry(), 30));
        arrayList.add(new C2935w(new Locale("", "GL").getDisplayCountry(), 299));
        arrayList.add(new C2935w(new Locale("", "GD").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "GP").getDisplayCountry(), 590));
        arrayList.add(new C2935w(new Locale("", "GU").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "GT").getDisplayCountry(), 502));
        arrayList.add(new C2935w(new Locale("", "GG").getDisplayCountry(), 44));
        arrayList.add(new C2935w(new Locale("", "GN").getDisplayCountry(), 224));
        arrayList.add(new C2935w(new Locale("", "GW").getDisplayCountry(), 245));
        arrayList.add(new C2935w(new Locale("", "GY").getDisplayCountry(), 592));
        arrayList.add(new C2935w(new Locale("", "HT").getDisplayCountry(), 509));
        arrayList.add(new C2935w(new Locale("", "HM").getDisplayCountry(), 672));
        arrayList.add(new C2935w(new Locale("", "HN").getDisplayCountry(), 504));
        arrayList.add(new C2935w(new Locale("", "HK").getDisplayCountry(), 852));
        arrayList.add(new C2935w(new Locale("", "HU").getDisplayCountry(), 36));
        arrayList.add(new C2935w(new Locale("", "IS").getDisplayCountry(), 354));
        arrayList.add(new C2935w(new Locale("", "IN").getDisplayCountry(), 91));
        arrayList.add(new C2935w(new Locale("", "ID").getDisplayCountry(), 62));
        arrayList.add(new C2935w(new Locale("", "IR").getDisplayCountry(), 98));
        arrayList.add(new C2935w(new Locale("", "IQ").getDisplayCountry(), 964));
        arrayList.add(new C2935w(new Locale("", "IE").getDisplayCountry(), 353));
        arrayList.add(new C2935w(new Locale("", "IM").getDisplayCountry(), 44));
        arrayList.add(new C2935w(new Locale("", "IL").getDisplayCountry(), 972));
        arrayList.add(new C2935w(new Locale("", "IT").getDisplayCountry(), 39));
        arrayList.add(new C2935w(new Locale("", "JM").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "JP").getDisplayCountry(), 81));
        arrayList.add(new C2935w(new Locale("", "JE").getDisplayCountry(), 44));
        arrayList.add(new C2935w(new Locale("", "JO").getDisplayCountry(), 962));
        arrayList.add(new C2935w(new Locale("", "KZ").getDisplayCountry(), 7));
        arrayList.add(new C2935w(new Locale("", "KE").getDisplayCountry(), 254));
        arrayList.add(new C2935w(new Locale("", "KI").getDisplayCountry(), 686));
        arrayList.add(new C2935w(new Locale("", "XK").getDisplayCountry(), 381));
        arrayList.add(new C2935w(new Locale("", "KW").getDisplayCountry(), 965));
        arrayList.add(new C2935w(new Locale("", ExpandedProductParsedResult.KILOGRAM).getDisplayCountry(), 996));
        arrayList.add(new C2935w(new Locale("", "LA").getDisplayCountry(), 856));
        arrayList.add(new C2935w(new Locale("", "LV").getDisplayCountry(), 371));
        arrayList.add(new C2935w(new Locale("", ExpandedProductParsedResult.POUND).getDisplayCountry(), 961));
        arrayList.add(new C2935w(new Locale("", "LS").getDisplayCountry(), 266));
        arrayList.add(new C2935w(new Locale("", "LR").getDisplayCountry(), 231));
        arrayList.add(new C2935w(new Locale("", "LY").getDisplayCountry(), 218));
        arrayList.add(new C2935w(new Locale("", "LI").getDisplayCountry(), HttpStatus.SC_LOCKED));
        arrayList.add(new C2935w(new Locale("", "LT").getDisplayCountry(), 370));
        arrayList.add(new C2935w(new Locale("", "LU").getDisplayCountry(), 352));
        arrayList.add(new C2935w(new Locale("", "MO").getDisplayCountry(), 853));
        arrayList.add(new C2935w(new Locale("", "MK").getDisplayCountry(), 389));
        arrayList.add(new C2935w(new Locale("", "MG").getDisplayCountry(), 261));
        arrayList.add(new C2935w(new Locale("", "MW").getDisplayCountry(), 265));
        arrayList.add(new C2935w(new Locale("", "MY").getDisplayCountry(), 60));
        arrayList.add(new C2935w(new Locale("", "MV").getDisplayCountry(), 960));
        arrayList.add(new C2935w(new Locale("", "ML").getDisplayCountry(), 223));
        arrayList.add(new C2935w(new Locale("", "MT").getDisplayCountry(), 356));
        arrayList.add(new C2935w(new Locale("", "MH").getDisplayCountry(), 692));
        arrayList.add(new C2935w(new Locale("", "MQ").getDisplayCountry(), 596));
        arrayList.add(new C2935w(new Locale("", "MR").getDisplayCountry(), 222));
        arrayList.add(new C2935w(new Locale("", "MU").getDisplayCountry(), 230));
        arrayList.add(new C2935w(new Locale("", "YT").getDisplayCountry(), 262));
        arrayList.add(new C2935w(new Locale("", "MX").getDisplayCountry(), 52));
        arrayList.add(new C2935w(new Locale("", "FM").getDisplayCountry(), 691));
        arrayList.add(new C2935w(new Locale("", "MD").getDisplayCountry(), 373));
        arrayList.add(new C2935w(new Locale("", "MC").getDisplayCountry(), 377));
        arrayList.add(new C2935w(new Locale("", "MN").getDisplayCountry(), 976));
        arrayList.add(new C2935w(new Locale("", "ME").getDisplayCountry(), 382));
        arrayList.add(new C2935w(new Locale("", "MS").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "MA").getDisplayCountry(), AVException.USER_MOBILEPHONE_MISSING));
        arrayList.add(new C2935w(new Locale("", "MZ").getDisplayCountry(), 258));
        arrayList.add(new C2935w(new Locale("", "MM").getDisplayCountry(), 95));
        arrayList.add(new C2935w(new Locale("", "NA").getDisplayCountry(), 264));
        arrayList.add(new C2935w(new Locale("", "NR").getDisplayCountry(), 674));
        arrayList.add(new C2935w(new Locale("", "NP").getDisplayCountry(), 977));
        arrayList.add(new C2935w(new Locale("", "NL").getDisplayCountry(), 31));
        arrayList.add(new C2935w(new Locale("", "NC").getDisplayCountry(), 687));
        arrayList.add(new C2935w(new Locale("", "NZ").getDisplayCountry(), 64));
        arrayList.add(new C2935w(new Locale("", "NI").getDisplayCountry(), 505));
        arrayList.add(new C2935w(new Locale("", "NE").getDisplayCountry(), 227));
        arrayList.add(new C2935w(new Locale("", "NG").getDisplayCountry(), 234));
        arrayList.add(new C2935w(new Locale("", "NU").getDisplayCountry(), 683));
        arrayList.add(new C2935w(new Locale("", "NF").getDisplayCountry(), 672));
        arrayList.add(new C2935w(new Locale("", "KP").getDisplayCountry(), 850));
        arrayList.add(new C2935w(new Locale("", "MP").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "NO").getDisplayCountry(), 47));
        arrayList.add(new C2935w(new Locale("", "OM").getDisplayCountry(), 968));
        arrayList.add(new C2935w(new Locale("", "PK").getDisplayCountry(), 92));
        arrayList.add(new C2935w(new Locale("", "PW").getDisplayCountry(), 680));
        arrayList.add(new C2935w(new Locale("", "PS").getDisplayCountry(), 970));
        arrayList.add(new C2935w(new Locale("", "PA").getDisplayCountry(), 507));
        arrayList.add(new C2935w(new Locale("", "PG").getDisplayCountry(), 675));
        arrayList.add(new C2935w(new Locale("", "PY").getDisplayCountry(), 595));
        arrayList.add(new C2935w(new Locale("", "PE").getDisplayCountry(), 51));
        arrayList.add(new C2935w(new Locale("", "PH").getDisplayCountry(), 63));
        arrayList.add(new C2935w(new Locale("", "PL").getDisplayCountry(), 48));
        arrayList.add(new C2935w(new Locale("", "PT").getDisplayCountry(), 351));
        arrayList.add(new C2935w(new Locale("", "PR").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "QA").getDisplayCountry(), 974));
        arrayList.add(new C2935w(new Locale("", "RE").getDisplayCountry(), 262));
        arrayList.add(new C2935w(new Locale("", "RO").getDisplayCountry(), 40));
        arrayList.add(new C2935w(new Locale("", "RU").getDisplayCountry(), 7));
        arrayList.add(new C2935w(new Locale("", "RW").getDisplayCountry(), 250));
        arrayList.add(new C2935w(new Locale("", "BL").getDisplayCountry(), 590));
        arrayList.add(new C2935w(new Locale("", "SH").getDisplayCountry(), 290));
        arrayList.add(new C2935w(new Locale("", "KN").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "LC").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "MF").getDisplayCountry(), 590));
        arrayList.add(new C2935w(new Locale("", "PM").getDisplayCountry(), d_ResultType.LONG_URL));
        arrayList.add(new C2935w(new Locale("", "VC").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "WS").getDisplayCountry(), 685));
        arrayList.add(new C2935w(new Locale("", "SM").getDisplayCountry(), 378));
        arrayList.add(new C2935w(new Locale("", "ST").getDisplayCountry(), 239));
        arrayList.add(new C2935w(new Locale("", "SA").getDisplayCountry(), 966));
        arrayList.add(new C2935w(new Locale("", "SN").getDisplayCountry(), 221));
        arrayList.add(new C2935w(new Locale("", "RS").getDisplayCountry(), 381));
        arrayList.add(new C2935w(new Locale("", "SC").getDisplayCountry(), 248));
        arrayList.add(new C2935w(new Locale("", "SL").getDisplayCountry(), 232));
        arrayList.add(new C2935w(new Locale("", "SG").getDisplayCountry(), 65));
        arrayList.add(new C2935w(new Locale("", "SX").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "SK").getDisplayCountry(), 421));
        arrayList.add(new C2935w(new Locale("", "SI").getDisplayCountry(), 386));
        arrayList.add(new C2935w(new Locale("", "SB").getDisplayCountry(), 677));
        arrayList.add(new C2935w(new Locale("", "SO").getDisplayCountry(), AVException.UNSUPPORTED_SERVICE));
        arrayList.add(new C2935w(new Locale("", "ZA").getDisplayCountry(), 27));
        arrayList.add(new C2935w(new Locale("", "GS").getDisplayCountry(), 500));
        arrayList.add(new C2935w(new Locale("", "KR").getDisplayCountry(), 82));
        arrayList.add(new C2935w(new Locale("", "SS").getDisplayCountry(), AVException.USER_DOESNOT_EXIST));
        arrayList.add(new C2935w(new Locale("", "ES").getDisplayCountry(), 34));
        arrayList.add(new C2935w(new Locale("", "LK").getDisplayCountry(), 94));
        arrayList.add(new C2935w(new Locale("", "SD").getDisplayCountry(), 249));
        arrayList.add(new C2935w(new Locale("", "SR").getDisplayCountry(), 597));
        arrayList.add(new C2935w(new Locale("", "SJ").getDisplayCountry(), 47));
        arrayList.add(new C2935w(new Locale("", "SZ").getDisplayCountry(), 268));
        arrayList.add(new C2935w(new Locale("", "SE").getDisplayCountry(), 46));
        arrayList.add(new C2935w(new Locale("", "CH").getDisplayCountry(), 41));
        arrayList.add(new C2935w(new Locale("", "SY").getDisplayCountry(), 963));
        arrayList.add(new C2935w(new Locale("", "TW").getDisplayCountry(), 886));
        arrayList.add(new C2935w(new Locale("", "TJ").getDisplayCountry(), 992));
        arrayList.add(new C2935w(new Locale("", "TZ").getDisplayCountry(), 255));
        arrayList.add(new C2935w(new Locale("", "TH").getDisplayCountry(), 66));
        arrayList.add(new C2935w(new Locale("", "TG").getDisplayCountry(), 228));
        arrayList.add(new C2935w(new Locale("", "TK").getDisplayCountry(), 690));
        arrayList.add(new C2935w(new Locale("", "TO").getDisplayCountry(), 676));
        arrayList.add(new C2935w(new Locale("", "TT").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "TN").getDisplayCountry(), 216));
        arrayList.add(new C2935w(new Locale("", "TR").getDisplayCountry(), 90));
        arrayList.add(new C2935w(new Locale("", "TM").getDisplayCountry(), 993));
        arrayList.add(new C2935w(new Locale("", "TC").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "TV").getDisplayCountry(), 688));
        arrayList.add(new C2935w(new Locale("", "VI").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "UG").getDisplayCountry(), 256));
        arrayList.add(new C2935w(new Locale("", "UA").getDisplayCountry(), 380));
        arrayList.add(new C2935w(new Locale("", "AE").getDisplayCountry(), 971));
        arrayList.add(new C2935w(new Locale("", "GB").getDisplayCountry(), 44));
        arrayList.add(new C2935w(new Locale("", "US").getDisplayCountry(), 1));
        arrayList.add(new C2935w(new Locale("", "UY").getDisplayCountry(), 598));
        arrayList.add(new C2935w(new Locale("", "UZ").getDisplayCountry(), 998));
        arrayList.add(new C2935w(new Locale("", "VU").getDisplayCountry(), 678));
        arrayList.add(new C2935w(new Locale("", "VA").getDisplayCountry(), 379));
        arrayList.add(new C2935w(new Locale("", "VE").getDisplayCountry(), 58));
        arrayList.add(new C2935w(new Locale("", "VN").getDisplayCountry(), 84));
        arrayList.add(new C2935w(new Locale("", "WF").getDisplayCountry(), 681));
        arrayList.add(new C2935w(new Locale("", "EH").getDisplayCountry(), AVException.USER_MOBILEPHONE_MISSING));
        arrayList.add(new C2935w(new Locale("", "YE").getDisplayCountry(), 967));
        arrayList.add(new C2935w(new Locale("", "ZM").getDisplayCountry(), 260));
        arrayList.add(new C2935w(new Locale("", "ZW").getDisplayCountry(), 263));
        Collections.sort(arrayList);
        return arrayList;
    }

    /* renamed from: a */
    protected void m14265a(List<C2935w> list) {
        if (this.f13356a != null) {
            this.f13356a.mo3631a(list);
        }
    }
}
